#!/usr/bin/env node
import { readFile, writeFile } from "node:fs/promises";
import { basename } from "node:path";
import { stdin as input, stderr, stdout } from "node:process";
import { createPrivateKey, createPublicKey } from "node:crypto";
import {
  ArxiumRpc, RpcError, encodeAuthorizeOperator, encodeGrantAttestation, encodeJoinValidator, encodeLeaveValidator,
  encodeRegisterBlsKey, encodeRevokeAttestation, encodeRevokeOperator, encodeStake, encodeTransfer,
  encodeUnstake, generateKey, isKeyFile, signAction, submitBody, unlockKey, verifyKeyFile,
  verifySignedAction, wrapPkcs8, encodeAddress, toHex, toKeyFile, PKCS8_ED25519_PREFIX, type ClaimTopic, type KeyFile,
} from "./index.js";

type Globals = { rpc: string; token?: string; key?: string; json: boolean; nonce?: number };
class UsageError extends Error {}
function output(value: unknown, json: boolean): void { stdout.write(json ? `${JSON.stringify(value, null, 2)}\n` : typeof value === "string" ? `${value}\n` : `${JSON.stringify(value, null, 2)}\n`); }
function parseGlobals(args: string[]): { globals: Globals; args: string[] } { let rpc = process.env.ARX_RPC ?? "http://127.0.0.1:8080", token = process.env.ARX_TOKEN, key = process.env.ARX_KEY, json = false, nonce: number | undefined; const rest: string[] = []; for (let i = 0; i < args.length; i++) { const arg = args[i]; if (arg === "--rpc") rpc = args[++i] ?? throwUsage("--rpc needs a value"); else if (arg === "--token") token = args[++i] ?? throwUsage("--token needs a value"); else if (arg === "--key") key = args[++i] ?? throwUsage("--key needs a value"); else if (arg === "--json") json = true; else if (arg === "--nonce") { const value = args[++i] ?? ""; if (!/^\d+$/.test(value)) throwUsage("--nonce needs a non-negative integer"); nonce = Number(value); } else rest.push(arg); } return { globals: { rpc, token, key, json, nonce }, args: rest }; }
function throwUsage(message: string): never { throw new UsageError(message); }
// Only stdin must be a terminal: the prompt goes to stderr, so `arx send … | jq` still prompts.
function prompt(label: string): Promise<string> { return new Promise((resolve) => { stderr.write(label); input.setRawMode(true); input.resume(); let value = ""; const onData = (chunk: Buffer) => { for (const char of chunk.toString("utf8")) { if (char === "\r" || char === "\n") { input.off("data", onData); input.setRawMode(false); input.pause(); stderr.write("\n"); resolve(value); return; } if (char === "\u0003") process.exit(130); if (char === "\u007f" || char === "\b") value = value.slice(0, -1); else value += char; } }; input.on("data", onData); }); }
async function passphrase(confirm = false): Promise<string> { if (process.env.ARX_PASSPHRASE) return process.env.ARX_PASSPHRASE; if (!input.isTTY) throw new UsageError("no passphrase: set ARX_PASSPHRASE or run interactively"); const value = await prompt("Passphrase: "); if (confirm && await prompt("Confirm passphrase: ") !== value) throw new UsageError("passphrases do not match"); return value; }
async function readKeyFile(path: string | undefined): Promise<KeyFile> { if (!path) throw new UsageError("--key or ARX_KEY is required"); const parsed: unknown = JSON.parse(await readFile(path, "utf8")); if (!isKeyFile(parsed)) throw new UsageError("invalid key file (or its address does not match its publicKey)"); return parsed; }
async function loadKey(path: string | undefined): Promise<{ file: KeyFile; privateKey: CryptoKey }> { const file = await readKeyFile(path); try { const privateKey = await unlockKey(file, await passphrase()); await verifyKeyFile(file, privateKey); return { file, privateKey }; } catch (error) { if (error instanceof UsageError) throw error; throw new UsageError(error instanceof Error ? error.message : String(error)); } }
async function readStdin(): Promise<string> { const chunks: Buffer[] = []; for await (const chunk of input) chunks.push(Buffer.from(chunk)); return Buffer.concat(chunks).toString("utf8"); }
function payload(action: string, args: string[]): Uint8Array { const amount = (index: number) => { const value = args[index]; if (!value || !/^\d+$/.test(value)) throwUsage("amount must be an integer IUM value"); return BigInt(value); }; switch (action) { case "transfer": return encodeTransfer(args[0] ?? throwUsage("transfer needs <to> <ium>"), amount(1)); case "stake": return encodeStake(args[0] ?? throwUsage("stake needs <validator> <ium>"), amount(1)); case "unstake": return encodeUnstake(args[0] ?? throwUsage("unstake needs <validator> <ium>"), amount(1)); case "join-validator": return encodeJoinValidator(args[0] ?? throwUsage("join-validator needs <validator> <ium> <bls-pubkey-hex> <bls-pop-hex>"), amount(1), hexArg(args[2]), hexArg(args[3])); case "leave-validator": return encodeLeaveValidator(args[0] ?? throwUsage("leave-validator needs <validator>")); case "register-bls-key": return encodeRegisterBlsKey(args[0] ?? throwUsage("register-bls-key needs <validator> <pubkey-hex> <pop-hex>"), hexArg(args[1]), hexArg(args[2])); case "authorize-operator": return encodeAuthorizeOperator(args[0] ?? throwUsage("authorize-operator needs <address>")); case "revoke-operator": return encodeRevokeOperator(); case "grant-attestation": return encodeGrantAttestation(args[0] ?? throwUsage("grant-attestation needs <subject> <hash> [topics] [jurisdiction]"), args[1] ?? throwUsage("grant-attestation needs <subject> <hash>"), args[2] ? args[2].split(",").map((topic) => ["kyc", "aml", "accredited", "jurisdiction"].includes(topic) ? topic as ClaimTopic : throwUsage(`unknown topic: ${topic} (kyc, aml, accredited, jurisdiction)`)) : [], args[3] ?? null); case "revoke-attestation": return encodeRevokeAttestation(args[0] ?? throwUsage("revoke-attestation needs <subject>")); default: throwUsage(`unsupported action: ${action}`); } }
function hexArg(value: string | undefined): Uint8Array { if (!value || !/^[0-9a-f]*$/i.test(value) || value.length % 2) throwUsage("expected even-length hex"); return Uint8Array.from(value.match(/../g)?.map((byte) => Number.parseInt(byte, 16)) ?? []); }
async function main(): Promise<void> { const { globals, args } = parseGlobals(process.argv.slice(2)); const [command, ...rest] = args; if (!command) throwUsage("use: arx keys|sign|submit|send|query|verify"); if (command === "keys") { const [operation, ...keyArgs] = rest; if (operation === "new") { const pass = await passphrase(true), generated = await generateKey(pass), file = toKeyFile(generated), destination = keyArgs[0] ?? `arxium-devnet-key-${generated.address.slice(4, 12)}.json`; await writeFile(destination, `${JSON.stringify(file, null, 2)}\n`, { mode: 0o600 }); output({ path: destination, address: file.address, publicKey: file.publicKey, network: file.network }, globals.json); return; } if (operation === "import" && keyArgs[0] === "--file") { const source = keyArgs[1] ?? throwUsage("keys import --file needs a path"), parsed = await readKeyFile(source); const destination = keyArgs[2] ?? basename(source); await writeFile(destination, `${JSON.stringify(parsed, null, 2)}\n`, { mode: 0o600 }); output({ path: destination, address: parsed.address }, globals.json); return; } if (operation === "import") { if (input.isTTY) throwUsage("pipe a 32-byte hex seed to `arx keys import`; seeds are never command arguments"); const seed = (await readStdin()).trim(); if (!/^[0-9a-f]{64}$/i.test(seed)) throwUsage("seed must be 32 bytes of hex"); const pkcs8 = Buffer.from(PKCS8_ED25519_PREFIX + seed, "hex"), publicJwk = createPublicKey(createPrivateKey({ key: pkcs8, format: "der", type: "pkcs8" })).export({ format: "jwk" }); if (!publicJwk.x) throw new Error("could not derive public key from seed"); const publicKey = Buffer.from(publicJwk.x, "base64url"), address = encodeAddress(publicKey), file = toKeyFile({ address, publicKey: toHex(publicKey), blob: await wrapPkcs8(pkcs8, await passphrase(true)) }), destination = keyArgs[0] ?? `arxium-devnet-key-${address.slice(4, 12)}.json`; await writeFile(destination, `${JSON.stringify(file, null, 2)}\n`, { mode: 0o600 }); output({ path: destination, address }, globals.json); return; } if (operation === "show") { const file = await readKeyFile(globals.key); output({ address: file.address, publicKey: file.publicKey, network: file.network }, globals.json); return; } throwUsage("use: arx keys new|import [destination]|import --file <file>|show"); }
  const rpc = new ArxiumRpc(globals);
  if (command === "sign" || command === "send") { const action = rest[0] ?? throwUsage(`${command} needs an action`), { file, privateKey } = await loadKey(globals.key), encoded = payload(action, rest.slice(1)); if (command === "sign") { const nonce = globals.nonce ?? await rpc.account<{ nonce: number }>(file.address).then((account) => account.nonce, (error: unknown) => { if (error instanceof RpcError && error.status === 404) return 0; throw error; }); output(submitBody(file.address, nonce, await signAction(privateKey, file.address, nonce, encoded), encoded), true); return; } output(await rpc.sendAction({ privateKey, sender: file.address, payload: encoded, finalized: true }), globals.json); return; }
  if (command === "submit") { const source = rest[0] ?? throwUsage("submit needs <file|->"), body = JSON.parse(source === "-" ? await readStdin() : await readFile(source, "utf8")); output(await rpc.submit(body) ?? { submitted: body.signature }, globals.json); return; }
  if (command === "verify") { const signature = rest[0] ?? throwUsage("verify needs <signature>"), status = await rpc.action(signature); if (status.status !== "confirmed") throw new Error(`action is ${status.status}`); const block = await rpc.block<{ finalized?: boolean; actions?: Array<{ sender: string; nonce: number; signature: string; payload: number[] }> }>(status.height); const action = block.actions?.find((item) => item.signature === signature); if (!block.finalized || !action || !await verifySignedAction(action)) throw new Error("action is not finalized with a valid signature"); output({ signature, finalized: true, signatureValid: true, height: status.height }, globals.json); return; }
  if (command === "query") { const [operation, value] = rest; const result = operation === "status" ? await rpc.status() : operation === "account" ? await rpc.account(value ?? throwUsage("account needs an address")) : operation === "block" ? (/^\d+$/.test(value ?? "") ? await rpc.block(Number(value)) : await rpc.blockByHash(value ?? throwUsage("block needs a height or hash"))) : operation === "action" ? await rpc.action(value ?? throwUsage("action needs a signature")) : operation === "validators" ? await rpc.validators() : operation === "finality" ? await rpc.finality() : operation === "search" ? await rpc.search(value ?? throwUsage("search needs a query")) : throwUsage("use: arx query status|account|block|action|validators|finality|search"); output(result, globals.json); return; }
  throwUsage(`unknown command: ${command}`); }
main().catch((error: unknown) => { const usage = error instanceof UsageError; stderr.write(`${error instanceof Error ? error.message : String(error)}\n`); process.exitCode = usage ? 2 : 1; });
