import { encodeAddress } from "./bech32.js";
import { asBuffer, fromHex, toHex } from "./bincode.js";
export const PBKDF2_ITERATIONS = 600_000;
export const PKCS8_ED25519_PREFIX = "302e020100300506032b657004220420";
export type KeyBlob = { version: 1; kdf: "PBKDF2-SHA256"; iterations: number; salt: string; iv: string; ciphertext: string };
/** The exact JSON document emitted by Console's `exportKey`. `network` is display metadata, not a signing domain. */
export type KeyFile = KeyBlob & { address: string; publicKey: string; network: string };
export type GeneratedKey = { address: string; publicKey: string; privateKey: CryptoKey; blob: KeyBlob };
const encodeBase64 = (bytes: Uint8Array): string => typeof btoa === "function" ? btoa(String.fromCharCode(...bytes)) : Buffer.from(bytes).toString("base64");
const decodeBase64 = (value: string): Uint8Array => typeof atob === "function" ? Uint8Array.from(atob(value), (char) => char.charCodeAt(0)) : new Uint8Array(Buffer.from(value, "base64"));
async function wrappingKey(passphrase: string, salt: Uint8Array, iterations: number): Promise<CryptoKey> { const material = await crypto.subtle.importKey("raw", asBuffer(new TextEncoder().encode(passphrase)), "PBKDF2", false, ["deriveKey"]); return crypto.subtle.deriveKey({ name: "PBKDF2", hash: "SHA-256", salt: asBuffer(salt), iterations }, material, { name: "AES-GCM", length: 256 }, false, ["encrypt", "decrypt"]); }
export async function generateKey(passphrase: string): Promise<GeneratedKey> { const pair = await crypto.subtle.generateKey("Ed25519", true, ["sign", "verify"]) as CryptoKeyPair, publicRaw = new Uint8Array(await crypto.subtle.exportKey("raw", pair.publicKey)), pkcs8 = new Uint8Array(await crypto.subtle.exportKey("pkcs8", pair.privateKey)), salt = crypto.getRandomValues(new Uint8Array(16)), iv = crypto.getRandomValues(new Uint8Array(12)); const ciphertext = new Uint8Array(await crypto.subtle.encrypt({ name: "AES-GCM", iv }, await wrappingKey(passphrase, salt, PBKDF2_ITERATIONS), pkcs8)); const privateKey = await crypto.subtle.importKey("pkcs8", pkcs8, "Ed25519", false, ["sign"]); pkcs8.fill(0); return { address: encodeAddress(publicRaw), publicKey: toHex(publicRaw), privateKey, blob: { version: 1, kdf: "PBKDF2-SHA256", iterations: PBKDF2_ITERATIONS, salt: encodeBase64(salt), iv: encodeBase64(iv), ciphertext: encodeBase64(ciphertext) } }; }
export async function wrapPkcs8(pkcs8: Uint8Array, passphrase: string): Promise<KeyBlob> { const salt = crypto.getRandomValues(new Uint8Array(16)), iv = crypto.getRandomValues(new Uint8Array(12)); const ciphertext = new Uint8Array(await crypto.subtle.encrypt({ name: "AES-GCM", iv }, await wrappingKey(passphrase, salt, PBKDF2_ITERATIONS), asBuffer(pkcs8))); return { version: 1, kdf: "PBKDF2-SHA256", iterations: PBKDF2_ITERATIONS, salt: encodeBase64(salt), iv: encodeBase64(iv), ciphertext: encodeBase64(ciphertext) }; }
/** Also checks `address` is the bech32 of `publicKey`, so a tampered file is rejected before any passphrase is asked for. */
export function isKeyFile(value: unknown): value is KeyFile { const key = value as Partial<KeyFile> | null; return !!key && key.version === 1 && key.kdf === "PBKDF2-SHA256" && typeof key.address === "string" && typeof key.publicKey === "string" && /^[0-9a-f]{64}$/i.test(key.publicKey) && encodeAddress(fromHex(key.publicKey)) === key.address && typeof key.network === "string" && typeof key.iterations === "number" && Number.isInteger(key.iterations) && key.iterations >= PBKDF2_ITERATIONS && [key.salt, key.iv, key.ciphertext].every((field) => typeof field === "string" && field.length > 0); }
/** The Console "Export key" / `arx keys new` document. Field order matches Console's historical export. */
export function toKeyFile(key: { address: string; publicKey: string; blob: KeyBlob }, network = "arx-devnet"): KeyFile { return { address: key.address, publicKey: key.publicKey, ...key.blob, network }; }
export async function unlockKey(blob: KeyBlob, passphrase: string): Promise<CryptoKey> { try { const pkcs8 = new Uint8Array(await crypto.subtle.decrypt({ name: "AES-GCM", iv: asBuffer(decodeBase64(blob.iv)) }, await wrappingKey(passphrase, decodeBase64(blob.salt), blob.iterations), asBuffer(decodeBase64(blob.ciphertext)))); const key = await crypto.subtle.importKey("pkcs8", asBuffer(pkcs8), "Ed25519", false, ["sign"]); pkcs8.fill(0); return key; } catch { throw new Error("wrong passphrase"); } }
export async function rewrapKey(blob: KeyBlob, oldPassphrase: string, newPassphrase: string): Promise<KeyBlob> { try { const pkcs8 = new Uint8Array(await crypto.subtle.decrypt({ name: "AES-GCM", iv: asBuffer(decodeBase64(blob.iv)) }, await wrappingKey(oldPassphrase, decodeBase64(blob.salt), blob.iterations), asBuffer(decodeBase64(blob.ciphertext)))); const wrapped = await wrapPkcs8(pkcs8, newPassphrase); pkcs8.fill(0); return wrapped; } catch { throw new Error("wrong passphrase"); } }
/** Confirms the decrypted private key belongs to the public address declared by the export. */
export async function verifyKeyFile(file: KeyFile, privateKey: CryptoKey): Promise<void> { const message = new TextEncoder().encode("arxium key file verification"); const signature = await crypto.subtle.sign("Ed25519", privateKey, asBuffer(message)); const publicKey = await crypto.subtle.importKey("raw", asBuffer(fromHex(file.publicKey)), "Ed25519", false, ["verify"]); if (encodeAddress(fromHex(file.publicKey)) !== file.address || !await crypto.subtle.verify("Ed25519", publicKey, signature, asBuffer(message))) throw new Error("key file address does not match decrypted key"); }
export async function importSeed(seedHex: string): Promise<CryptoKey> { if (!/^[0-9a-f]{64}$/i.test(seedHex)) throw new Error("seed must be 32 bytes of hex"); return crypto.subtle.importKey("pkcs8", asBuffer(fromHex(PKCS8_ED25519_PREFIX + seedHex)), "Ed25519", false, ["sign"]); }
