[package]
name = "send-tx"
version = "0.1.0"
edition = "2021"
license.workspace = true

[[bin]]
name = "send-tx"
path = "src/main.rs"

[dependencies]
xc-primitives = { workspace = true }
circuit-staking = { workspace = true }
node = { workspace = true }
runtime = { workspace = true }
ed25519-dalek = { workspace = true }
serde_json = { workspace = true }
hex = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
