[package]
name = "toy-chain"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
ed25519-dalek = { workspace = true }
hex = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

serde = { workspace = true, features = ["derive"] }

xc-primitives = { workspace = true }
xc-storage = { workspace = true }
xc-mempool = { workspace = true }
xc-executor = { workspace = true }
circuit-rwa-asset = { workspace = true }
