[package]
name = "toy-chain"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true, features = ["derive"] }

xc-primitives = { workspace = true }
xc-storage = { workspace = true }
xc-executor = { workspace = true }
runtime-api = { workspace = true }
xc-evidence = { workspace = true }
xc-chain-spec = { workspace = true }
node = { workspace = true }
circuit-rwa-asset = { workspace = true }
