[package]
name = "xc-mempool"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
xc-primitives = { workspace = true }
xc-storage = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
bincode = { workspace = true }
