[package]
name = "runtime-api"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true, features = ["derive"] }

xc-primitives = { workspace = true }
xc-storage = { workspace = true }
xc-executor = { workspace = true }
xc-evidence = { workspace = true }
