[package]
name = "load-test"
version = "0.1.0"
edition = "2021"
license.workspace = true

[[bin]]
name = "load-test"
path = "src/main.rs"

[dependencies]
xc-primitives = { workspace = true }
arxd-node = { workspace = true }
arxd-runtime = { workspace = true }
ed25519-dalek = { workspace = true }
serde_json = { workspace = true }
hex = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
