[package]
name = "arxd-finality"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
tracing = { workspace = true }
serde = { workspace = true }
xc-primitives = { workspace = true }
xc-bls = { workspace = true }
xc-storage = { workspace = true }

[dev-dependencies]
ed25519-dalek = { workspace = true }
