[package]
name = "admin-slash"
version = "0.1.0"
edition = "2021"
license.workspace = true

[[bin]]
name = "admin-slash"
path = "src/main.rs"

[dependencies]
xc-primitives = { workspace = true }
xc-storage = { workspace = true }
circuit-staking = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
