[package]
name = "evidence"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
thiserror = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
xc-primitives = { workspace = true }
xc-storage = { workspace = true }
xc-mempool = { workspace = true }

[dev-dependencies]
ed25519-dalek = { workspace = true }
